### ISSUE TITLE
Shutdown design

### ISSUE THREAD

**Issue by agherzan** [crashvb/upsmon-docker#1]
How is this implementation handling shutdown operations in upsmon? I fail to see anything that targets the host for this operation.

**Comment by crashvb** [comment]
It's not ...

Propagation of a system shutdown is handled by the container runtime / orchestrator and intercepted by `supervisord`, which is then propagated to `upsmon` via [stopsignal](http://supervisord.org/configuration.html#program-x-section-values) (default: `SIGTERM`).

Triggering of a system shutdown, using the default `SHUTDOWNCMD` upsmon.conf value, would require installing the [systemd-sysv](https://packages.ubuntu.com/jammy/systemd-sysv) package to provide `/sbin/shutdown`; although other [options](https://stackoverflow.com/a/65916870) exist. Either way, the container needs additional capabilities / privileges.

For my own systems, I modified `SHUTDOWNCMD` create a file (flag) in a volume, and created a corresponding native package to monitor for the flag and bridge between containers, VMs, systemd, etc before invoking `shutdown`. (e.g. remote volume mounts can hang if the switch between the two systems cuts out, leaving things in a bad state, causing lengthy timeouts)

**Comment by agherzan** [comment]
That's very much what I ended up doing, too. One small thing, though: what did you mean when you mentioned bridging the containers before invoking shutdown?

**Comment by crashvb** [comment]
Some of my systems run containers, virtual machines, and other system-level (systemd) services that are inter-dependent; most of the time across host boundaries, but there are edge cases within a host for select systems.

For example a system-level `nslcd` + `nscd` services that queries a containerized `slapd` instance, which also backs a virtualized windows domain. In theory, nscd should fill in the gaps during startup / shutdown while slapd is initializing / tearing down, and the systemd services provided by the hypervisor should propagate events to the VMs; but in practice there are race conditions that make things non-deterministic. I know with enough time / effort it should be possible to tweak the dependencies and fill in the gaps at the systemd level (one system to rule them all, right?), but codifying a few steps in a shell script has a better effort-to-effectiveness ratio, even if it is an ugly design.

**Comment by crashvb** [comment]
After thought: In minimalistic system, such as `k3os`, where the non-containerized foot print is transient, or easily recreatable with cloudinit, perhase such complexities wouldn't be needed and stricter assertions could be made about the runtime environment. IIRC, k3os has two containerd namespaces, one for system-level services, and one for "user-level" services; the latter would be ideal for running this image ...
